= Hodnocení
:toc:

== Pravidla zkoušení v ZS 2023/2024

Zkouška z předmětu NI-KRY bude mít následovní obsah:

* Zkouška se bude se skládat z 3 otázek, které budou kladeny studentovi postupně.
* Student dostane otázku, na kterou bude mít cca 5 minut na přípravu, a následně bude student odpovídat na udělenou otázku a doplňující dotazy zkoušejícího.
* Pak bude zkoušejícím udělena známka, a to tak, že za každou otázku může získat student maximálně 20 bodů, tj. celkově maximálně 60 bodů. Body z cvičení budou tvořit 40% známky, tzn. že student si může z cvičení „přinést“ maximálně 40 bodů.

Zkouška je tedy ústní kontaktní s přípravou:

. Zkoušený bude přítomen společně v místnosti se zkoušejícím u vyhrazeného místa u stolu. 
. Po zadání otázky bude student mít cca 5 minut na písemnou přípravu, a pak bude bezprostředně tázán.
. Zkouška bude ukončena hodnocením.

== Hodnocení cvičení, zápočet
Můžete získat až 

* 30 bodů za aktivitu a řešení úloh a 
* 10 bodů z testu. 

Pro získání zápočtu potřebujete **minimálně 21 bodů**. Zápočet je podmínkou pro účast na zkoušce.

== Zkouška, celkové hodnocení


|====
| Známka | Bodové rozmezí | Slovní hodnocení

| A      | 90 a více      | výborně
| B      | 80-89          | velmi dobře
| C      | 70-79          | dobře
| D      | 60-69          | uspokojivě
| E      | 50-59          | dostatečně
| F      | méně než 50    | nedostatečně
|====

Hodnocení se řídí Studijním a zkušebním řádem ČVUT, který najdete na stránce s https://www.cvut.cz/vnitrni-predpisy#szr[vnitřními předpisy ČVUT].
